### ISSUE TITLE
When the email password has been set

### ISSUE THREAD

**Issue by gjxwwww8888** [TeamWiseFlow/wiseflow#104]
![image](https://github.com/user-attachments/assets/d121a2f8-210d-4e9e-8f42-ab40da1d1e20)
![image](https://github.com/user-attachments/assets/c8678bcc-61b4-45f2-abc0-798c55787b0f)

**Comment by bigbrother666sh** [comment]
- The first time you run the docker container, you may encounter an error, which is normal because you have not yet created an admin account for the pb repository. 

At this point, keep the container running, open your browser to http://127.0.0.1:8090/_/, and follow the prompts to create an admin account (must use an email), then fill in the created admin email (again, must be an email) and password into the .env file, and restart the container.
